services:
  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - prestashop_network
  mysql:
    platform: linux/x86_64
    container_name: ebiz_mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
    volumes:
      - ebiz_mysql:/var/lib/mysql
  prestashop:
    platform: linux/x86_64
    container_name: prestashop
    build: .
    restart: unless-stopped
    depends_on:
      - mysql
      - maildev
    ports:
      - 8080:80
      - 443:443
    environment:
      DB_SERVER: ebiz_mysql
      DB_NAME: prestashop
      DB_USER: ${DB_USER}
      DB_PASSWD: ${DB_PASSWD}
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost:8080
      MAILDEV_SMTP_HOST: maildev
      MAILDEV_SMTP_PORT: 1025
    networks:
      - prestashop_network
    volumes:
      - ./../shop:/var/www/html
networks:
  prestashop_network:
volumes:
  ebiz_mysql:
