services:
  mysql:
    platform: linux/x86_64
    container_name: ebiz_mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
    volumes:
      - ebiz_mysql:/var/lib/mysql
  prestashop:
    platform: linux/x86_64
    container_name: prestashop
    build: .
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
      - 443:443
    environment:
      DB_SERVER: ebiz_mysql
      DB_NAME: prestashop
      DB_USER: ${DB_USER}
      DB_PASSWD: ${DB_PASSWD}
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost:8080
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 512M
        reservations:
          cpus: '1.0'
          memory: 256M
    networks:
      - prestashop_network
    volumes:
