parent: classic
name: child_classic
display_name: Child theme of classic's theme
version: 1.0.1
assets:
  use_parent_assets: false
  js:
      all:
        - id: analytics
          path: assets/js/ga.js
          priority: 10
          position: bottom
        - id: ga-function
          path: https://www.googletagmanager.com/gtag/js?id=G-KY75ZPQK62
          priority: 5
          position: bottom
