CATEGORIES_TO_ADD = [
    'Minerały - Bryłki',
    'Minerały - Geody',
    'Minerały - kolekcjonerskie',
    'Kryształy i minerały',
    'Minerały - Otoczaki',
    'Minerały - Plastry',
    'Minerały - Zgłady',
    'Podstawki pod minerały',
    'Biżuteria srebrna',
    'Bransoletki',
    'Breloczki',
    'Broszki, agrafki',
    'Kamienie do oprawy',
    'Kolczyki',
    'Naszyjniki',
    'Wisiorki i zawieszki',
    'Metaloplastyka',
    'Sznury z kamieni',
    'Buteleczki z kryształami i kamieniami naturalnymi',
    'Do dekoracji',
    'Figurki zwierząt',
    'Kamienne groty',
    'Jajka z kamieni',
    'Kamienie do masażu',
    'Kostki z kamienia',
    'Kule z kamieni',
    'Misy, talerze, patery i mydelniczki z kamienia',
    'Moździerze z kamienia',
    'Obeliski z kamieni naturalnych',
    'Odpromienniki z kamieni i minerałów',
    'Piramidy',
    'Podstawki pod kule, jajka, tealight',
    'Baran (21.III-20.IV)',
    'Byk (21.IV-20.V)',
    'Bliźnięta (21.V-21.VI)',
    'Rak (22.VI - 22.VII)',
    'Lew (23. VII-23. VIII)',
    'Panna (24. VIII-23. IX)',
    'Waga (24.IX-23.X)',
    'Skorpion (24.X-22.XI)',
    'Strzelec (23.XI-21.XII)',
    'Koziorożec (22 XII-20 I)',
    'Wodnik (21.I-19.II)',
    'Ryby (20.II-20.III )',
    'Indochinit',
    'Amonity',
    'Flora karbońska',
    'Goniatyty',
    'Jeżowce',
    'Koralowce',
    'Krewetki',
    'Łodzikowce',
    'Małże',
    'Mozazaury',
    'Ramienionogi (Brachiopoda)',
    'Rekiny',
    'Skamieniałe drewno',
    'Stromatolit',
    'Ślimaki',
    'Trylobity',
]
PRODUCTS_TO_PUSH = 1000
MAX_PRODUCTS_IN_SUBCATEGORY = 20